const configBuilder = require('webpack-focus').configBuilder;
const path = require('path');

const customConfig = {
    externals: {
        'focus-core': 'FocusCore',
        'focus-core/application': {root: ['FocusCore', 'application']},
        'focus-core/application/built-in-store': {root: ['FocusCore', 'application', 'builtInStore']},
        'focus-core/component': {root: ['FocusCore', 'component']},
        'focus-core/component/builder': {root: ['FocusCore', 'component', 'builder']},
        'focus-core/component/types': {root: ['FocusCore', 'component', 'types']},
        'focus-core/definition': {root: ['FocusCore', 'definition']},
        'focus-core/definition/domain': {root: ['FocusCore', 'definition', 'domain']},
        'focus-core/definition/domain/container': {root: ['FocusCore', 'definition', 'domain', 'container']},
        'focus-core/definition/entity': {root: ['FocusCore', 'definition', 'entity']},
        'focus-core/definition/entity/builder': {root: ['FocusCore', 'definition', 'entity', 'builder']},
        'focus-core/definition/entity/container': {root: ['FocusCore', 'definition', 'entity', 'container']},
        'focus-core/definition/formatter': {root: ['FocusCore', 'definition', 'formatter']},
        'focus-core/definition/formatter/number': {root: ['FocusCore', 'definition', 'formatter', 'number']},
        'focus-core/definition/validator': {root: ['FocusCore', 'definition', 'validator']},
        'focus-core/definition/validator/validate': {root: ['FocusCore', 'definition', 'validator', 'validate']},
        'focus-core/definition/validator/date': {root: ['FocusCore', 'definition', 'validator', 'date']},
        'focus-core/definition/validator/email': {root: ['FocusCore', 'definition', 'validator', 'email']},
        'focus-core/definition/validator/number': {root: ['FocusCore', 'definition', 'validator', 'number']},
        'focus-core/definition/validator/string-length': {root: ['FocusCore', 'definition', 'validator', 'stringLength']},
        'focus-core/dispatcher': {root: ['FocusCore', 'dispatcher']},
        'focus-core/exception': {root: ['FocusCore', 'exception']},
        'focus-core/exception/argument-invalid-exception': {root: ['FocusCore', 'exception', 'ArgumentInvalidException']},
        'focus-core/exception/argument-null-exception': {root: ['FocusCore', 'exception', 'ArgumentNullException']},
        'focus-core/exception/custom-exception': {root: ['FocusCore', 'exception', 'CustomException']},
        'focus-core/exception/dependency-exception': {root: ['FocusCore', 'exception', 'DependencyException']},
        'focus-core/exception/focus-exception': {root: ['FocusCore', 'exception', 'FocusException']},
        'focus-core/exception/not-implemented-exception': {root: ['FocusCore', 'exception', 'NotImplementedException']},
        'focus-core/history': {root: ['FocusCore', 'history']},
        'focus-core/list': {root: ['FocusCore', 'list']},
        'focus-core/list/action-builder': {root: ['FocusCore', 'list', 'actionBuilder']},
        'focus-core/list/load-action': {root: ['FocusCore', 'list', 'loadAction']},
        'focus-core/message': {root: ['FocusCore', 'message']},
        'focus-core/message/built-in-store': {root: ['FocusCore', 'message', 'builtInStore']},
        'focus-core/network': {root: ['FocusCore', 'network']},
        'focus-core/network/cors': {root: ['FocusCore', 'network', 'cors']},
        'focus-core/network/fetch': {root: ['FocusCore', 'network', 'fetch']},
        'focus-core/network/cancellable-promise-builder': {root: ['FocusCore', 'network', 'cancellablePromiseBuilder']},
        'focus-core/network/built-in-store': {root: ['FocusCore', 'network', 'builtInStore']},
        'focus-core/network/config': {root: ['FocusCore', 'network', 'config']},
        'focus-core/network/error-parsing': {root: ['FocusCore', 'network', 'errorParsing']},
        'focus-core/reference': {root: ['FocusCore', 'reference']},
        'focus-core/reference/built-in-store': {root: ['FocusCore', 'reference', 'storeGetter']},
        'focus-core/reference/built-in-action': {root: ['FocusCore', 'reference', 'builtInAction']},
        'focus-core/reference/config': {root: ['FocusCore', 'reference', 'config']},
        'focus-core/reference/builder': {root: ['FocusCore', 'reference', 'builder']},
        'focus-core/router': {root: ['FocusCore', 'router']},
        'focus-core/search': {root: ['FocusCore', 'search']},
        'focus-core/search/built-in-store': {root: ['FocusCore', 'search', 'builtInStore']},
        'focus-core/search/action-builder': {root: ['FocusCore', 'search', 'actionBuilder']},
        'focus-core/store': {root: ['FocusCore', 'store']},
        'focus-core/store/application': {root: ['FocusCore', 'store', 'application']},
        'focus-core/store/application/store': {root: ['FocusCore', 'store', 'application', 'store']},
        'focus-core/store/list': {root: ['FocusCore', 'store', 'list']},
        'focus-core/store/message': {root: ['FocusCore', 'store', 'message']},
        'focus-core/store/message/store': {root: ['FocusCore', 'store', 'message']},
        'focus-core/store/reference': {root: ['FocusCore', 'store', 'reference']},
        'focus-core/store/request': {root: ['FocusCore', 'store', 'request']},
        'focus-core/store/request/store': {root: ['FocusCore', 'store', 'request']},
        'focus-core/store/search': {root: ['FocusCore', 'store', 'search']},
        'focus-core/store/search/advanced-search': {root: ['FocusCore', 'store', 'search', 'advancedSearch']},
        'focus-core/store/search/quick-search': {root: ['FocusCore', 'store', 'search', 'quickSearch']},
        'focus-core/store/user': {root: ['FocusCore', 'store', 'user']},
        'focus-core/translation': {root: ['FocusCore', 'translation']},
        'focus-core/user': {root: ['FocusCore', 'user']},
        'focus-core/user/login': {root: ['FocusCore', 'user']},
        'focus-core/user/profile': {root: ['FocusCore', 'user']},
        'focus-core/util': {root: ['FocusCore', 'util']},
        'focus-core/util/object': {root: ['FocusCore', 'util', 'object']},
        'focus-core/util/string': {root: ['FocusCore', 'util', 'string']},
        'focus-core/util/string/check': {root: ['FocusCore', 'util', 'string', 'check']},
        'focus-core/util/url': {root: ['FocusCore', 'util', 'url']},

        react: 'React',
        'react-dom': 'ReactDOM',
        moment: 'moment',
        jquery: 'jQuery',
        numeral: 'numeral'
    },
    module: {
        preLoaders: [
            {
                test: /material-design-lite\/material/,
                loader: 'exports?componentHandler'
            }
        ]
    }
};
module.exports = configBuilder(customConfig);
