
import TestUtils from 'react-addons-test-utils';
import React from 'react';
import ReactDOM from 'react-dom';

import storeConnectBehaviour from '../connect';
const { renderIntoDocument, Simulate } = TestUtils;

import store from 'focus-core/store';
import dispatcher from 'focus-core/dispatcher';
const { CoreStore } = store;


describe('The store connect behaviour', () => {
    describe('when called without storeConf', () => {
        it('should throw an error', () => {
            expect(() => storeConnectBehaviour()).toThrow('connectToStores: you need to provide an array of store config.');
        });
    });
    describe('when called without getState', () => {
        it('should throw an error', () => {
            expect(() => storeConnectBehaviour([])).toThrow('connectToStores: you need to provide function to read state from store.');
        });
    });
    describe('when called with correct argument', () => {
        it('should return a function', () => {
            expect(() => storeConnectBehaviour([], () => { })).toBeInstanceOf(Function);
        });
    });
    describe('when called with a store', () => {
        let renderComponent;
        const storeChangeSpy = jest.fn();
        const conectedComponentRenderSpy = jest.fn();
        const newStore = new CoreStore({ definition: { papa: 'papa', lopez: 'lopez' } });
        const connector = storeConnectBehaviour(
            [{ store: newStore, properties: ['papa', 'lopez'] }],
            (props) => { const storeValue = newStore.getValue(); storeChangeSpy(storeValue); return storeValue; }
        );
        const Component = (props) => { conectedComponentRenderSpy(props); return <div>{JSON.stringify(props)}</div>; };
        const ConnectedComponent = connector(Component);
        beforeEach(
            () => {
                renderComponent = renderIntoDocument(<ConnectedComponent testProps='testPropsValue' />);
            }
        );
        it('should call the getState method on mounting', () => {
            expect(storeChangeSpy).toHaveBeenCalledTimes(1);
            expect(storeChangeSpy).toHaveBeenCalledWith({});
            expect(conectedComponentRenderSpy).toHaveBeenCalledTimes(1);
            expect(conectedComponentRenderSpy).toHaveBeenCalledWith({ testProps: 'testPropsValue' });
        });
        describe('when a value with two nodes is dispatched', () => {
            beforeEach(() => {
                dispatcher.handleViewAction({
                    data: {
                        lopez: 'joe',
                        papa: 'singe'
                    },
                    type: 'update'
                });
            });
            it('the store change spy should have been called twice', () => {
                expect(storeChangeSpy).toHaveBeenCalledTimes(3); //Mounting, joe, singe
            });
            it('the component shoud have been rendered twice', () => {
                expect(conectedComponentRenderSpy).toHaveBeenCalledTimes(2);
            });
            it('the html generated by the component should contains props and state', () => {
                const domNode = ReactDOM.findDOMNode(renderComponent);
                expect(JSON.parse(domNode.innerHTML)).toEqual({ lopez: 'joe', papa: 'singe', testProps: 'testPropsValue' });
            });
        });

    });
});
