module.exports = {
    autocomplete: require('./autocomplete'),
    block: require('./block'),
    button: require('./button'),
    empty: require('./empty'),
    field: require('./field'),
    form: require('./form'),
    img: require('./img'),
    i18n: require('./i18n'),
    icon: require('./icon'),
    input: require('./input'),
    label: require('./label'),
    panel: require('./panel'),
    select: require('./select'),
    selectAction: require('./select-action'),
    stickyNavigation: require('./sticky-navigation'),
    title: require('./title'),
    topicDisplayer: require('./topic-displayer'),
    list: require('./list'),
    mixin: require('./mixin'),
    display: require('./display'),
    detail: require('./detail'),
    progressBar: require('./progress-bar'),
    role: require('./role')
};
